# This is a basic workflow to help you get started with Actions

name: connections-config-ci

on:
  push:
      branches: [ main ]
      paths: ['config_payload.json']
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: .
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
 
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # Specify the Python version you need
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Add any other dependencies here

      - name: Run the script
        run: python skyflow_connections_update.py 
        env:
          VAULT_OWNER_SA_CREDENTIALS: ${{secrets.VAULT_OWNER_SA_CREDENTIALS}}
          REQUEST_BIN_BASE_URL: "https://ens3s06g2e69r.x.pipedream.net"
          REQUEST_BIN_RELATIVE_PATH: "/sample/post/request/"
          SKYFLOW_ACCOUNT_ID: "t50877c6ada449308cff528e38467614"
          SKYFLOW_OUTBOUND_CONNECTION_ENDPOINT: "https://manage.skyflowapis.com/v1/gateway/outboundRoutes"
          VAULT_ID: "w6063d10d50d4386807dd7794f714577"
          SKYFLOW_CONNECTION_ID: "u8403776c3914f16b53ead7579ffebd6"
